/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Path gates = Paths.get("resources/gates.js");
        System.out.println(makeJavaScript(gates));
    }

    public static String makeJavaScript(Path file) {
        String errors = "error Message: ";
        String clear = "success";
        boolean anyError = false;
        Scanner fileScanner;

        try {

            fileScanner = new Scanner(new File(file.toUri()));
            int currentLineNumber = 1;

            while(fileScanner.hasNextLine()) {
                String currentLine = fileScanner.nextLine();
                if(!currentLine.endsWith(";")) {
                    errors += "\n" + "line " + currentLineNumber + " missing semicolon";
                    anyError = true;
                }
                currentLineNumber++;
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return anyError ? errors : clear;
    }

}
