/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRestaurantInstance() {
        Restaurant newRestaurant = new Restaurant("fogo de chao", 4);

        String output = "restaurant: fogo de chao = 0.0 stars + 4 price";
        assertEquals(output, newRestaurant.toString());
    }

    @Test public void testReviewInstance() {
        Review nr = new Review("meh", "j.gold", 2);
        System.out.println(nr.toString());
    }

    @Test public void testAddReview() {
        Restaurant newRestaurant = new Restaurant("fogo de chao", 4);
        Review r = new Review("good", "j.gold", 1);
        newRestaurant.addReview(r);
        Review nr = new Review("bomb", "j.gold", 4);
        newRestaurant.addReview(nr);

        String output = "restaurant: fogo de chao = 2.5 stars + 4 price";
        assertEquals(output, newRestaurant.toString());
    }

    @Test public void testShopInstance() {
        Shop newShop = new Shop("Book Worm", "A book shop", 2);

        String output = "This is a shop: Book Worm Description: A book shop Price Range: 2";
        assertEquals(output, newShop.toString());
    }

    @Test public void testShopReview() {
        Shop shop = new Shop("Some Shop", "yay capitalism", 3);
        Review newReview = new Review("pricey", "average joe", 2);
        shop.addReview(newReview);

        Review runner = shop.reviews;
        assertEquals("average joe", runner.author);
    }

    @Test public void testTheaterInstance() {
        Theater newTheater = new Theater("AMC", "star wars");

        String output = "This is a Theater: AMC Movies: star wars";
        assertEquals(output, newTheater.toString());
    }

    @Test public void testMovieReview() {
        Theater newTheater = new Theater("AMC", "star wars");
        MovieReview movieReview = new MovieReview("just ok", "joe public", 3, "star wars");
        newTheater.addReview(movieReview);

        // Why did I have to cast newTheater?
        MovieReview runner = (MovieReview) newTheater.reviews;
        String output = "star wars";
        assertEquals(output, runner.movie);
    }

    @Test public void testAddMovie() {
        Theater amc = new Theater("AMC", "star wars");
        amc.addMovie("ford v. ferrari");

        String output = "This is a Theater: AMC Movies: star wars -- ford v. ferrari";
        assertEquals(output, amc.toString());
    }
}
