/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRestaurantInstance() {
        Restaurant newRestaurant = new Restaurant("fogo de chao", 4);

        String output = "restaurant: fogo de chao = 0.0 stars + 4 price";
        assertEquals(output, newRestaurant.toString());
    }

    @Test public void testReviewInstance() {
        Review nr = new Review("meh", "j.gold", 2);
        System.out.println(nr.toString());
    }

    @Test public void testAddReview() {
        Restaurant newRestaurant = new Restaurant("fogo de chao", 4);
        Review r = new Review("good", "j.gold", 1);
        newRestaurant.addReview(r);
        Review nr = new Review("bomb", "j.gold", 4);
        newRestaurant.addReview(nr);

        String output = "restaurant: fogo de chao = 2.5 stars + 4 price";
        assertEquals(output, newRestaurant.toString());
    }
}
